// Command api is the Andipatti Animal Feed System Go backend HTTP server.
package main

import (
	"context"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/andipatti/feedmate/services/api/internal/config"
	"github.com/andipatti/feedmate/services/api/internal/dbctx"
	"github.com/andipatti/feedmate/services/api/internal/domain/contra"
	"github.com/andipatti/feedmate/services/api/internal/domain/customer"
	"github.com/andipatti/feedmate/services/api/internal/domain/devicepairing"
	"github.com/andipatti/feedmate/services/api/internal/domain/eod"
	"github.com/andipatti/feedmate/services/api/internal/domain/identity"
	"github.com/andipatti/feedmate/services/api/internal/domain/location"
	"github.com/andipatti/feedmate/services/api/internal/domain/masterdata"
	"github.com/andipatti/feedmate/services/api/internal/domain/payment"
	"github.com/andipatti/feedmate/services/api/internal/domain/pos"
	"github.com/andipatti/feedmate/services/api/internal/domain/procurement"
	"github.com/andipatti/feedmate/services/api/internal/domain/product"
	"github.com/andipatti/feedmate/services/api/internal/domain/reports"
	"github.com/andipatti/feedmate/services/api/internal/domain/returns"
	"github.com/andipatti/feedmate/services/api/internal/domain/supplier"
	"github.com/andipatti/feedmate/services/api/internal/httpapi"
	appmw "github.com/andipatti/feedmate/services/api/internal/middleware"
	"github.com/andipatti/feedmate/services/api/internal/paymentprovider"
)

func main() {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))
	slog.SetDefault(logger)

	cfg, err := config.Load()
	if err != nil {
		slog.Error("configuration error", "error", err)
		os.Exit(1)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	db, err := dbctx.Connect(ctx, cfg.DatabaseURL, cfg.DatabaseAdminURL)
	cancel()
	if err != nil {
		slog.Error("database connection failed", "error", err)
		os.Exit(1)
	}
	defer db.Close()

	identitySvc := identity.NewService(db, cfg.JWTSigningKey, cfg.AccessTokenTTL, cfg.RefreshTokenTTL, cfg.BcryptCost)
	productSvc := product.NewService(db)
	posSvc := pos.NewService(db)
	procurementSvc := procurement.NewService(db)
	returnsSvc := returns.NewService(db)
	contraSvc := contra.NewService(db)
	eodSvc := eod.NewService(db)
	reportsSvc := reports.NewService(db)
	locationSvc := location.NewService(db)
	devicePairingSvc := devicepairing.NewService(db)
	customerSvc := customer.NewService(db)
	supplierSvc := supplier.NewService(db)
	masterDataSvc := masterdata.NewService(db)

	var provider paymentprovider.Provider
	switch cfg.PaymentProvider {
	case "sandbox":
		provider = paymentprovider.NewSandboxProvider(cfg.SandboxWebhookSecret)
	default:
		slog.Error("unknown PAYMENT_PROVIDER", "value", cfg.PaymentProvider)
		os.Exit(1)
	}
	paymentSvc := payment.NewService(db, provider)

	authHandlers := &httpapi.AuthHandlers{Identity: identitySvc}
	healthHandlers := &httpapi.HealthHandlers{DB: db}
	productHandlers := &httpapi.ProductHandlers{Product: productSvc}
	posHandlers := &httpapi.POSHandlers{POS: posSvc}
	procurementHandlers := &httpapi.ProcurementHandlers{Procurement: procurementSvc}
	returnsHandlers := &httpapi.ReturnsHandlers{Returns: returnsSvc}
	paymentHandlers := &httpapi.PaymentHandlers{Payment: paymentSvc}
	contraHandlers := &httpapi.ContraHandlers{Contra: contraSvc}
	eodHandlers := &httpapi.EODHandlers{EOD: eodSvc}
	reportsHandlers := &httpapi.ReportsHandlers{Reports: reportsSvc}
	locationHandlers := &httpapi.LocationHandlers{Location: locationSvc}
	deviceHandlers := &httpapi.DeviceHandlers{DevicePairing: devicePairingSvc}
	customerHandlers := &httpapi.CustomerHandlers{Customer: customerSvc}
	supplierHandlers := &httpapi.SupplierHandlers{Supplier: supplierSvc}
	masterDataHandlers := &httpapi.MasterDataHandlers{MasterData: masterDataSvc}

	r := chi.NewRouter()
	r.Use(appmw.RequestID)
	r.Use(appmw.Recoverer)

	r.Get("/health/live", healthHandlers.Live)
	r.Get("/health/ready", healthHandlers.Ready)

	r.Route("/api/v1", func(r chi.Router) {
		r.Post("/auth/login", authHandlers.Login)
		r.Post("/auth/refresh", authHandlers.Refresh)
		r.Post("/auth/logout", authHandlers.Logout)

		// A brand new device has no access token — its only credential is a
		// short-lived pairing code generated by an already-authenticated user
		// on another device (see devicepairing.Service). Deliberately not
		// behind RequireAuth.
		r.Post("/devices/register", deviceHandlers.RegisterDevice)

		// Payment webhooks are called by the external provider, which cannot
		// present one of our bearer tokens — authentication here is the
		// provider's cryptographic signature (verified inside the handler),
		// never RequireAuth.
		r.Post("/payments/webhooks/sandbox", paymentHandlers.SandboxWebhook)

		r.Group(func(r chi.Router) {
			r.Use(appmw.RequireAuth(cfg.JWTSigningKey))

			r.Get("/products/search", productHandlers.Search)
			r.Get("/products", productHandlers.List)
			r.Get("/products/{id}", productHandlers.Get)
			r.With(appmw.RequirePermission("product.manage")).Post("/products", productHandlers.Create)
			r.With(appmw.RequirePermission("product.manage")).Put("/products/{id}", productHandlers.Update)
			r.With(appmw.RequirePermission("product.manage")).Post("/products/{id}/status", productHandlers.SetStatus)

			r.Get("/categories", masterDataHandlers.ListCategories)
			r.Get("/brands", masterDataHandlers.ListBrands)
			r.Get("/uoms", masterDataHandlers.ListUOMs)
			r.Get("/tax-profiles", masterDataHandlers.ListTaxProfiles)

			r.With(appmw.RequirePermission("pos.sell")).Post("/pos/quote", posHandlers.Quote)
			r.With(appmw.RequirePermission("pos.sell")).Post("/pos/invoices", posHandlers.FinalizeInvoice)
			r.With(appmw.RequirePermission("return.create")).Get("/pos/invoices", posHandlers.GetInvoiceForReturn)
			r.With(appmw.RequirePermission("pos.sell")).Get("/pos/invoices/history", posHandlers.ListInvoices)
			r.With(appmw.RequirePermission("pos.sell")).Get("/pos/invoices/{id}", posHandlers.GetInvoiceDetail)

			r.With(appmw.RequirePermission("pos.sell")).Get("/locations", locationHandlers.List)

			r.With(appmw.RequirePermission("device.manage")).Post("/devices/pairing-codes", deviceHandlers.GeneratePairingCode)

			r.With(appmw.RequirePermission("grn.post")).Post("/procurement/grns", procurementHandlers.PostGRN)
			r.With(appmw.RequirePermission("grn.post")).Get("/procurement/grns", procurementHandlers.ListGRNs)
			r.With(appmw.RequirePermission("grn.post")).Get("/procurement/grns/{id}", procurementHandlers.GetGRNDetail)

			r.With(appmw.RequirePermission("return.create")).Post("/pos/returns", returnsHandlers.PostReturn)

			r.With(appmw.RequirePermission("pos.sell")).Post("/payments/receipt-intents", paymentHandlers.CreateReceiptIntent)
			r.With(appmw.RequirePermission("pos.sell")).Get("/payments/intents/{id}", paymentHandlers.GetIntentStatus)
			r.With(appmw.RequirePermission("pos.sell")).Post("/payments/receipts", paymentHandlers.RecordManualReceipt)
			r.With(appmw.RequirePermission("supplier.manage")).Post("/payments/supplier-payments", paymentHandlers.RecordSupplierPayment)

			r.With(appmw.RequirePermission("contra.approve")).Post("/contra", contraHandlers.PostContra)

			r.With(appmw.RequirePermission("cash.eod_close")).Post("/eod/open", eodHandlers.OpenSession)
			r.With(appmw.RequirePermission("cash.eod_close")).Post("/eod/close", eodHandlers.CloseSession)
			r.With(appmw.RequirePermission("eod.reopen")).Post("/eod/reopen", eodHandlers.ReopenSession)
			r.With(appmw.RequirePermission("cash.eod_close")).Get("/eod", eodHandlers.GetSession)

			r.With(appmw.RequirePermission("report.view")).Get("/reports/sales-summary", reportsHandlers.SalesSummary)
			r.With(appmw.RequirePermission("report.view")).Get("/reports/stock-on-hand", reportsHandlers.StockOnHand)
			r.With(appmw.RequirePermission("report.view")).Get("/reports/customer-balances", reportsHandlers.CustomerBalances)
			r.With(appmw.RequirePermission("report.view")).Get("/reports/eod-history", reportsHandlers.EODHistory)

			r.Get("/customers", customerHandlers.List)
			r.Get("/customers/{id}", customerHandlers.Get)
			r.Get("/customers/{id}/ledger", customerHandlers.Ledger)
			r.With(appmw.RequirePermission("credit.configure")).Post("/customers", customerHandlers.Create)
			r.With(appmw.RequirePermission("credit.configure")).Put("/customers/{id}/credit-limit", customerHandlers.SetCreditLimit)

			r.Get("/suppliers", supplierHandlers.List)
			r.Get("/suppliers/{id}", supplierHandlers.Get)
			r.Get("/suppliers/{id}/ledger", supplierHandlers.Ledger)
			r.With(appmw.RequirePermission("supplier.manage")).Post("/suppliers", supplierHandlers.Create)
			r.With(appmw.RequirePermission("supplier.manage")).Put("/suppliers/{id}", supplierHandlers.Update)
			r.With(appmw.RequirePermission("supplier.manage")).Post("/suppliers/{id}/status", supplierHandlers.SetStatus)

			// Further authenticated routes (inventory, etc.) are registered
			// here as each domain module is implemented.
		})
	})

	srv := &http.Server{
		Addr:              cfg.HTTPAddr,
		Handler:           r,
		ReadHeaderTimeout: 5 * time.Second,
	}

	go func() {
		slog.Info("api server starting", "addr", cfg.HTTPAddr, "env", cfg.AppEnv)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("server error", "error", err)
			os.Exit(1)
		}
	}()

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, syscall.SIGINT, syscall.SIGTERM)
	<-stop

	slog.Info("shutting down")
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer shutdownCancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		slog.Error("graceful shutdown failed", "error", err)
	}
}
